# CapiBot Self-Hosted Installer for Windows
# Usage: irm https://capibot.io/install.ps1 | iex
#    or: .\install.ps1 -LicenseKey CAPI-XXXX-XXXX-XXXX-XXXX

param(
	[string]$LicenseKey
)

$ErrorActionPreference = "Stop"

$CapiBotDir = "$env:USERPROFILE\capibot"
$ComposeUrl = "https://capibot.io/self-hosted"

# ── Helpers ──

function Write-Log  { param($msg) Write-Host "[✓] $msg" -ForegroundColor Green }
function Write-Warn { param($msg) Write-Host "[!] $msg" -ForegroundColor Yellow }
function Write-Err  { param($msg) Write-Host "[✗] $msg" -ForegroundColor Red }
function Write-Info { param($msg) Write-Host "[→] $msg" -ForegroundColor Cyan }

function Get-RandomHex {
	param([int]$Bytes = 32)
	$bytes_arr = New-Object byte[] $Bytes
	[System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes_arr)
	return ($bytes_arr | ForEach-Object { $_.ToString("x2") }) -join ''
}

function Get-RandomBase64 {
	param([int]$Bytes = 32)
	$bytes_arr = New-Object byte[] $Bytes
	[System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes_arr)
	return [Convert]::ToBase64String($bytes_arr) -replace '[/+=]','' | ForEach-Object { $_.Substring(0, [Math]::Min(44, $_.Length)) }
}

function Get-RandomPassword {
	param([int]$Length = 16)
	$chars = 'abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789'
	$bytes_arr = New-Object byte[] $Length
	[System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes_arr)
	return -join ($bytes_arr | ForEach-Object { $chars[$_ % $chars.Length] })
}

# ── Header ──

Write-Host ""
Write-Host "╔══════════════════════════════════════╗" -ForegroundColor White
Write-Host "║      CapiBot Self-Hosted Installer   ║" -ForegroundColor White
Write-Host "╚══════════════════════════════════════╝" -ForegroundColor White
Write-Host ""

# ── License Key ──

if (-not $LicenseKey) {
	$LicenseKey = Read-Host "Enter your license key (CAPI-XXXX-XXXX-XXXX-XXXX)"
}

if ($LicenseKey -notmatch '^CAPI-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}$') {
	Write-Err "Invalid license key format. Expected: CAPI-XXXX-XXXX-XXXX-XXXX"
	exit 1
}
Write-Log "License key accepted"

# ── Check Docker ──

$dockerCmd = Get-Command docker -ErrorAction SilentlyContinue
if ($dockerCmd) {
	$dockerVersion = & docker --version 2>&1
	Write-Log "Docker found: $dockerVersion"
} else {
	Write-Err "Docker Desktop is not installed."
	Write-Host ""
	Write-Host "  Please install Docker Desktop for Windows:" -ForegroundColor Yellow
	Write-Host "  https://docs.docker.com/desktop/install/windows-install/" -ForegroundColor Cyan
	Write-Host ""
	Write-Host "  After installing, restart this script." -ForegroundColor Yellow
	exit 1
}

# Check Docker is running
try {
	& docker info 2>&1 | Out-Null
	Write-Log "Docker is running"
} catch {
	Write-Err "Docker is installed but not running. Please start Docker Desktop and try again."
	exit 1
}

# Check docker compose
try {
	& docker compose version 2>&1 | Out-Null
	Write-Log "Docker Compose found"
} catch {
	Write-Err "Docker Compose not found. Please update Docker Desktop."
	exit 1
}

# ── Create directory ──

Write-Info "Installing to $CapiBotDir"
New-Item -ItemType Directory -Path $CapiBotDir -Force | Out-Null
Set-Location $CapiBotDir

# ── Download compose files ──

Write-Info "Downloading configuration files..."
Invoke-WebRequest -Uri "$ComposeUrl/docker-compose.yml" -OutFile "docker-compose.yml" -UseBasicParsing
Write-Log "Downloaded docker-compose.yml"

# ── Generate secrets ──

Write-Info "Generating secure secrets..."
$DbPassword = Get-RandomHex -Bytes 24
$ApiKey = Get-RandomHex -Bytes 32
$JwtSecret = Get-RandomHex -Bytes 32
$GatewayToken = Get-RandomBase64 -Bytes 32
$SessionSecret = Get-RandomHex -Bytes 32

$AdminPassword = Read-Host "Choose an admin password (or press Enter to generate one)"
if (-not $AdminPassword) {
	$AdminPassword = Get-RandomPassword
	Write-Warn "Generated admin password: $AdminPassword"
}

# ── Write .env ──

$timestamp = (Get-Date -Format "yyyy-MM-dd HH:mm:ss") + " UTC"
$envContent = @"
# CapiBot Self-Hosted Configuration
# Generated by install.ps1 on $timestamp

# License
CAPIBOT_LICENSE_KEY=$LicenseKey

# Database
DB_PASSWORD=$DbPassword

# Security
CAPIBOT_API_KEY=$ApiKey
JWT_SECRET=$JwtSecret
CAPIBOT_GATEWAY_TOKEN=$GatewayToken

# Admin Login
CAPIBOT_ADMIN_PASSWORD=$AdminPassword

# LLM Providers — add at least one, or configure in the dashboard under Integrations
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...
# GOOGLE_AI_API_KEY=...
# ALIBABA_API_KEY=sk-sp-...
# KIMI_API_KEY=...
# GLM_API_KEY=...
# MINIMAX_API_KEY=...

# Provider Priority (comma-separated, first available wins)
# CAPIBOT_PROVIDER_PRIORITY=anthropic,gemini,alibaba,kimi,glm,minimax,ollama

# Ollama LLM fallback (optional — embeddings are handled automatically)
# OLLAMA_MODEL=llama3.2

# Telegram Bot (optional)
# TELEGRAM_BOT_TOKEN=123456:ABC-DEF...

# Ports (defaults shown)
# CAPIBOT_API_PORT=3000
# CAPIBOT_WS_PORT=3001
# MC_PORT=3002

# WebSocket origins
CAPIBOT_WS_ALLOWED_ORIGINS=http://localhost:3002
"@
Set-Content -Path ".env" -Value $envContent -Encoding UTF8
Write-Log "Generated .env"

# ── Write .env.mc ──

$envMcContent = @"
# Mission Control Configuration
# Generated by install.ps1 on $timestamp

SESSION_SECRET=$SessionSecret
CAPIBOT_API_KEY=$ApiKey
CAPIBOT_GATEWAY_TOKEN=$GatewayToken
MC_ALLOWED_HOSTS=localhost,127.0.0.1
"@
Set-Content -Path ".env.mc" -Value $envMcContent -Encoding UTF8
Write-Log "Generated .env.mc"

# ── Save credentials ──

$credContent = @"
======================================
  CapiBot Self-Hosted Credentials
======================================

Dashboard:     http://localhost:3002
API:           http://localhost:3000
WebSocket:     ws://localhost:3001

Admin Login:   admin / $AdminPassword
API Key:       $ApiKey
License Key:   $LicenseKey

Generated: $timestamp

IMPORTANT: Keep this file secure. Delete it after saving credentials elsewhere.
"@
Set-Content -Path "credentials.txt" -Value $credContent -Encoding UTF8
Write-Log "Saved credentials to credentials.txt"

# ── Start the stack ──

Write-Host ""
Write-Info "Starting CapiBot..."
Write-Host ""
& docker compose pull 2>&1 | Where-Object { $_ -ne "" }
& docker compose up -d

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════════╗" -ForegroundColor White
Write-Host "║               CapiBot is starting!                  ║" -ForegroundColor White
Write-Host "╠══════════════════════════════════════════════════════╣" -ForegroundColor White
Write-Host "║                                                      ║" -ForegroundColor White
Write-Host "║  Dashboard:  http://localhost:3002                   ║" -ForegroundColor White
Write-Host "║  Username:   admin                                   ║" -ForegroundColor White
Write-Host "║  Password:   $AdminPassword$((' ' * (26 - $AdminPassword.Length)))║" -ForegroundColor White
Write-Host "║                                                      ║" -ForegroundColor White
Write-Host "╚══════════════════════════════════════════════════════╝" -ForegroundColor White
Write-Host ""
Write-Info "Containers are starting up (this may take a minute on first run)."
Write-Info "Run 'docker compose logs -f' in $CapiBotDir to watch progress."
Write-Host ""
Write-Warn "Next step: Add an LLM API key in the dashboard under Integrations → Keys"
Write-Warn "Or edit $CapiBotDir\.env and add your key, then run: docker compose restart capibot"
Write-Host ""
Write-Log "Installation complete!"
Write-Host ""
