#!/usr/bin/env bash
set -euo pipefail

# CapiBot Self-Hosted Installer
# Usage: curl -fsSL https://capibot.io/install.sh | bash -s <LICENSE_KEY>
#    or: curl -fsSL https://capibot.io/install.sh | bash  (will prompt for key)

CAPIBOT_DIR="${CAPIBOT_DIR:-$HOME/capibot}"
COMPOSE_URL="https://capibot.io/self-hosted"

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

log()   { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
err()   { echo -e "${RED}[✗]${NC} $1"; }
info()  { echo -e "${CYAN}[→]${NC} $1"; }

echo ""
echo -e "${BOLD}╔══════════════════════════════════════╗${NC}"
echo -e "${BOLD}║      CapiBot Self-Hosted Installer   ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════╝${NC}"
echo ""

# ── License Key ──
LICENSE_KEY="${1:-}"
if [ -z "$LICENSE_KEY" ]; then
	echo -n "Enter your license key (CAPI-XXXX-XXXX-XXXX-XXXX): "
	read -r LICENSE_KEY
fi

if [[ ! "$LICENSE_KEY" =~ ^CAPI-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}-[A-F0-9]{4}$ ]]; then
	err "Invalid license key format. Expected: CAPI-XXXX-XXXX-XXXX-XXXX"
	exit 1
fi
log "License key accepted"

# ── Check / Install Docker ──
if command -v docker &>/dev/null; then
	log "Docker found: $(docker --version)"
else
	warn "Docker not found — installing..."
	if [ "$(uname)" = "Linux" ]; then
		curl -fsSL https://get.docker.com | sh
		sudo systemctl enable docker
		sudo systemctl start docker
		# Add current user to docker group
		sudo usermod -aG docker "$USER"
		warn "Added $USER to docker group. You may need to log out and back in."
		log "Docker installed"
	else
		err "Please install Docker Desktop manually: https://docs.docker.com/get-docker/"
		exit 1
	fi
fi

# Verify docker compose
if docker compose version &>/dev/null; then
	log "Docker Compose found"
elif docker-compose version &>/dev/null; then
	err "Legacy docker-compose found. Please upgrade to Docker Compose v2: https://docs.docker.com/compose/install/"
	exit 1
else
	err "Docker Compose not found. Please install it: https://docs.docker.com/compose/install/"
	exit 1
fi

# ── Create directory ──
info "Installing to ${CAPIBOT_DIR}"
mkdir -p "$CAPIBOT_DIR"
cd "$CAPIBOT_DIR"

# ── Download compose files ──
info "Downloading configuration files..."
curl -fsSL "${COMPOSE_URL}/docker-compose.yml" -o docker-compose.yml
log "Downloaded docker-compose.yml"

# ── Generate secrets ──
info "Generating secure secrets..."
DB_PASSWORD=$(openssl rand -hex 24)
API_KEY=$(openssl rand -hex 32)
JWT_SECRET=$(openssl rand -hex 32)
GATEWAY_TOKEN=$(openssl rand -base64 32 | tr -d '/+=' | head -c 44)
SESSION_SECRET=$(openssl rand -hex 32)

echo -n "Choose an admin password (or press Enter to generate one): "
read -r ADMIN_PASSWORD
if [ -z "$ADMIN_PASSWORD" ]; then
	ADMIN_PASSWORD=$(openssl rand -base64 16 | tr -d '/+=' | head -c 16)
	warn "Generated admin password: ${BOLD}${ADMIN_PASSWORD}${NC}"
fi

# ── Write .env ──
cat > .env << ENVEOF
# CapiBot Self-Hosted Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# License
CAPIBOT_LICENSE_KEY=${LICENSE_KEY}

# Database
DB_PASSWORD=${DB_PASSWORD}

# Security
CAPIBOT_API_KEY=${API_KEY}
JWT_SECRET=${JWT_SECRET}
CAPIBOT_GATEWAY_TOKEN=${GATEWAY_TOKEN}

# Admin Login
CAPIBOT_ADMIN_PASSWORD=${ADMIN_PASSWORD}

# LLM Providers — add at least one, or configure in the dashboard under Integrations
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...
# GOOGLE_AI_API_KEY=...
# ALIBABA_API_KEY=sk-sp-...
# KIMI_API_KEY=...
# GLM_API_KEY=...
# MINIMAX_API_KEY=...

# Provider Priority (comma-separated, first available wins)
# CAPIBOT_PROVIDER_PRIORITY=anthropic,gemini,alibaba,kimi,glm,minimax,ollama

# Ollama LLM fallback (optional — embeddings are handled automatically)
# OLLAMA_MODEL=llama3.2

# Telegram Bot (optional)
# TELEGRAM_BOT_TOKEN=123456:ABC-DEF...

# Ports (defaults shown)
# CAPIBOT_API_PORT=3000
# CAPIBOT_WS_PORT=3001
# MC_PORT=3002

# WebSocket origins
CAPIBOT_WS_ALLOWED_ORIGINS=http://localhost:3002
ENVEOF
chmod 600 .env
log "Generated .env"

# ── Write .env.mc ──
cat > .env.mc << MCEOF
# Mission Control Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

SESSION_SECRET=${SESSION_SECRET}
CAPIBOT_API_KEY=${API_KEY}
CAPIBOT_GATEWAY_TOKEN=${GATEWAY_TOKEN}
MC_ALLOWED_HOSTS=localhost,127.0.0.1
MCEOF
chmod 600 .env.mc
log "Generated .env.mc"

# ── Save credentials ──
cat > credentials.txt << CREDEOF
╔══════════════════════════════════════╗
║   CapiBot Self-Hosted Credentials   ║
╚══════════════════════════════════════╝

Dashboard:     http://localhost:3002
API:           http://localhost:3000
WebSocket:     ws://localhost:3001

Admin Login:   admin / ${ADMIN_PASSWORD}
API Key:       ${API_KEY}
License Key:   ${LICENSE_KEY}

Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

IMPORTANT: Keep this file secure. Delete it after saving credentials elsewhere.
CREDEOF
chmod 600 credentials.txt
log "Saved credentials to credentials.txt"

# ── Start the stack ──
echo ""
info "Starting CapiBot..."
echo ""
docker compose pull 2>&1 | grep -v "^$$" || true
docker compose up -d

echo ""
echo -e "${BOLD}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}║               CapiBot is starting!                  ║${NC}"
echo -e "${BOLD}╠══════════════════════════════════════════════════════╣${NC}"
echo -e "${BOLD}║                                                      ║${NC}"
echo -e "${BOLD}║  Dashboard:  ${CYAN}http://localhost:3002${NC}${BOLD}                  ║${NC}"
echo -e "${BOLD}║  Username:   ${GREEN}admin${NC}${BOLD}                                  ║${NC}"
echo -e "${BOLD}║  Password:   ${GREEN}${ADMIN_PASSWORD}${NC}${BOLD}$(printf '%*s' $((26 - ${#ADMIN_PASSWORD})) '')║${NC}"
echo -e "${BOLD}║                                                      ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
info "Containers are starting up (this may take a minute on first run)."
info "Run ${BOLD}docker compose logs -f${NC} in ${CAPIBOT_DIR} to watch progress."
echo ""
warn "Next step: Add an LLM API key in the dashboard under Integrations → Keys"
warn "Or edit ${CAPIBOT_DIR}/.env and add your key, then run: docker compose restart capibot"
echo ""
log "Installation complete!"
echo ""
